version: '3.8'
services:
  gateway:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./gateway:/app  # Bind mount for hot-reload
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && node server.js"
    networks:
      - raft_network

  # --- THE RAFT CLUSTER ---
  replica1:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./replica:/app  # Notice this points to a shared "replica" folder
    environment:
      - REPLICA_ID=1
      - PORT=8081
      - HEARTBEAT_INTERVAL_MS=500
      - ELECTION_TIMEOUT_MIN_MS=2000
      - ELECTION_TIMEOUT_MAX_MS=3500
    ports:
      - "8081:8081"
    command: sh -c "npm install && npm run dev"
    networks:
      - raft_network

  replica2:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./replica:/app
    environment:
      - REPLICA_ID=2
      - PORT=8082
      - HEARTBEAT_INTERVAL_MS=500
      - ELECTION_TIMEOUT_MIN_MS=2000
      - ELECTION_TIMEOUT_MAX_MS=3500
    ports:
      - "8082:8082"
    command: sh -c "npm install && npm run dev"
    networks:
      - raft_network

  replica3:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./replica:/app
    environment:
      - REPLICA_ID=3
      - PORT=8083
      - HEARTBEAT_INTERVAL_MS=500
      - ELECTION_TIMEOUT_MIN_MS=2000
      - ELECTION_TIMEOUT_MAX_MS=3500
    ports:
      - "8083:8083"
    command: sh -c "npm install && npm run dev"
    networks:
      - raft_network

networks:
  raft_network:
    driver: bridge
